### ISSUE TITLE
test.sh fails when vim-diff-enhanced is installed by Vundle

### ISSUE THREAD

**Issue by advocateddrummer** [chrisbra/vim-diff-enhanced#1]
I've installed the plugin and when I try to run the test.sh script, it looks in `~/.vim/plugin` for the EnhancedDiff.vim file which, for me at least, actually exists in `~/.vim/bundle/vim-enhanced-diff/plugin`

I don't know the general way to fix this as I don't know where all the other plugin managers might also stick the .vim file or I'd try to fix this myself and send you a pull request. Maybe you didn't mean for this to be used by other users?

Also, you've misspelled  "readable" as "readabile" on line 27 of EnhancedDiff.txt.

Thanks very much for all your contributions to the vim world!

**Comment by chrisbra** [comment]
Hi Ethan!

On Do, 26 Feb 2015, Ethan Alan Hereth wrote:

> I've installed the plugin and when I try to run the test.sh script, it looks in `~/.vim/plugin` for the EnhancedDiff.vim file which, for me at least, actually exists in `~/.vim/bundle/vim-enhanced-diff/plugin`
> 
> I don't know the general way to fix this as I don't know where all the other plugin managers might also stick the .vim file or I'd try to fix this myself and send you a pull request. Maybe you didn't mean for this to be used by other users?

Thanks for the feedback, I'll look into it.

> Thanks very much for all your contributions to the vim world!

Thanks for the nice feedback. Very motivating ;)

Best,

## Christian

Man könnte froh sein, wenn die Luft so rein wäre wie das Bier.
        -- Richard von Weizsäcker

**Comment by advocateddrummer** [comment]
I cannot even get the test.sh script to work even by fixing the path; it complains about not being able to find the EnhancedDiff functions. And ultimately, the script breaks when the EnhancedDiff_normal.txt file fails to exist. I don't understand this stuff enough to understand why...

**Comment by chrisbra** [comment]
The test is mainly for myself for testing, that the generated ed-style diff works correctly. However I have made some adjustments to the test.sh script and it should now work correctly, if when the plugin is not installed into ~/.vim/plugin/

**Comment by advocateddrummer** [comment]
That seems to have done the trick! Thank you!
