### ISSUE TITLE
diff moved lines

### ISSUE THREAD

**Issue by 1-61803** [chrisbra/vim-diff-enhanced#10]
Could you add an algorithm that diffs moved lines?

I'm thinking [Notepad++ Compare plugin](https://sourceforge.net/projects/npp-compare/). I haven't found a similar implementation for unix/linux in general, nor  for `vim` in particular.

![Notepad++ Compare plugin screenshot](http://i.stack.imgur.com/jF26O.png)

**Comment by chrisbra** [comment]
Am 2016-03-01 13:33, schrieb 1-61803:

> Could you add an algorithm that diffs moved lines?
> 
> I'm thinking Notepad++ Compare plugin [1]. I haven't found a similar
> implementation for unix/linux in general, nor for vim in particular.

this plugin is merely a wrapper around git diff and vimdiff. I would be 
happy to
implement something like this, but I am afraid, that neither git-diff 
nor
vimdiff actually support this.

**Comment by 1-61803** [comment]
If you could implement this, it would make an excellent tool in `vim` and for most `*nix` users.

**Comment by chrisbra** [comment]
Am 2016-03-01 15:14, schrieb 1-61803:

> If you could implement this, it would make an excellent tool in vim
> and for most *nix users.

I agree, but I am the wrong person to ask :(
