### ISSUE TITLE
Creating unnecesary temporary files and or duplicate work slows down opening many diffs

### ISSUE THREAD

**Issue by aktau** [chrisbra/vim-diff-enhanced#11]
Hi! I have a setup whereby I diff many pairs of files in the same Vim buffer. The process goes more or less like this:

```
$ vim -"special diff mode" : $file1 $file2 : $file3 $file4 : ...
```

The "special diff mode" script basically opens every pair of files in a two buffers and puts them in diff mode. These files are immutable in my case.

I noticed that it's very slow for many pairs of files, so I used `execsnoop(1)`. The following appears to be the "core" of diffing two files:

```
 27327 /bin/zsh -c (git diff --diff-algorithm=patience -U0 /tmp/vWllDdr/71 /tmp/vWllDdr/72) >/tmp/vWllDdr/74 2>&1
 27327 /bin/zsh -c (git diff --diff-algorithm=patience -U0 /tmp/vWllDdr/71 /tmp/vWllDdr/72) >/tmp/vWllDdr/75 2>&1
```

It seems at least one of those two is redundant (if tempfiles 71 and 72 are not changed in between, that is). I'm also not sure why `/tmp/vWllDdr/71` and `/tmp/vWllDdr/72` are used as sources at all. The real immutable files should be openable immediately. This might have something do with with the way this multi-buffer setup I mentioned above is done. The relevant part:

``` vim
let s:idx = 0
while s:idx < argc()
  if s:idx != 0
      tabnew
  endif
  execute 'silent edit ' fnameescape(argv(s:idx))
  execute 'silent ' s:vertical_modifier ' diffsplit ' fnameescape(argv(s:idx + 1))
  wincmd =
  let s:idx += 2
endwhile
```

Perhaps I'm doing something wrong here? Can I somehow mark those files as readonly when loading them into buffers such that vim doesn't attempt to make a copy? 

Later I'll test with all of my plugins disabled, to see if there might be something else causing the duplication. I just wanted to collect my thoughts.

Another obvious way of speeding this up would be to run all of these things in parallel, but I don't think Vim supports such a thing.

Another possible source of slowness that I haven't benchmarked: starting a shell for every command (`zsh -c`).

**Comment by aktau** [comment]
I think the duplication I'm seeing is because of: http://vim.1045645.n5.nabble.com/vim-diff-td5708773.html. Vim "tests" the diffexpr by passing dummy files filled with "line1" and "line2" to it.

I wonder whether it's possible to disable this behaviour after it has verified this once per session.

As for the temporary files. The only way to avoid this (I think) is to someho avoid the `edit/diffsplit` steps and somehow make Vim create this "natively". I have absolutely no idea whether this is possible, or whether Vim would do what I want.

**Comment by chrisbra** [comment]
Yeah, I remember about the test of the diffexpr. To change this behaviour would mean to patch vim, so this is no solution.

As for the temporary files, I don't think this is possible currently.

**Comment by chrisbra** [comment]
I am closing this, as the current Vim (starting with patch [8.1.360](https://github.com/vim/vim/commit/e828b7621cf9065a3582be0c4dd1e0e846e335bf)) include the xdiff library which gets rid of all those workaround.

(This also means, that this plugin isn't needed anymore)
