### ISSUE TITLE
NeoVim compatibility

### ISSUE THREAD

**Issue by phmarek** [chrisbra/vim-diff-enhanced#12]
Hi,

with Neovim 0.1.5 I get

```
The EnhancedDiff Plugin needs at least a Vim version 8.0
```

although it should have the same capabilities, right?

**Comment by chrisbra** [comment]
probably I don't know. Try this patch:

``` patch
@@ -16,10 +16,11 @@
 let s:cpo= &cpo
 if exists("g:loaded_enhanced_diff") || &cp
     finish
-elseif v:version < 800
+elseif !exists("*systemlist")
     echohl WarningMsg
-    echomsg "The EnhancedDiff Plugin needs at least a Vim version 8.0"
+    echomsg "The EnhancedDiff Plugin needs a new Vim or NeoVim"
     echohl Normal
+    finish
 endif
 set cpo&vim
 let g:loaded_enhanced_diff = 1
```

**Comment by phmarek** [comment]
Thanks a lot for the quick fix!

Yes, now it starts normally; `:PatienceDiff` shows that it works, too.

`:EnhancedDiffIgnorePat` alone isn't enough on nvim, though; I need to run `:EnhancedDiff default` to use the patterns. Might be worth a hint in the manual.

Thanks a lot!
