### ISSUE TITLE
How to achieve filler lines from README images

### ISSUE THREAD

**Issue by lewis6991** [chrisbra/vim-diff-enhanced#15]
Just a question.

I noticed in the images on the README, the filler lines look like they are using the ```–``` character as apposed to the default ```-``` character. Did you do anything special to achieve that?

Sorry for raising an issue to ask this. Didn't know how to ask otherwise.

Thanks

**Comment by chrisbra** [comment]
I think, I have been using an em-dash for that. See [here](https://github.com/chrisbra/vim_dotfiles/blob/master/vimrc#L277)

**Comment by lewis6991** [comment]
Awesome thanks!
