### ISSUE TITLE
Maybe include a sample file... not sure if working

### ISSUE THREAD

**Issue by Astara** [chrisbra/vim-diff-enhanced#16]
I tried this and tried a few "CustomDiff" algorithms and then did a "diffu", but didn't see
any changes in my diff window.  It's possible it had something to do with my file choices, but
dunno.  Also just noticed, I have "-w" set in my .vimrc file:
~/.vimrc:
let &diffopt+="-w"

I compared two ".h" files: 
samplexity.h & samplexity.h.orig

Thanks!

(Attached)

[samplexity.h.txt](https://github.com/chrisbra/vim-diff-enhanced/files/843068/samplexity.h.txt)
[samplexity.h.orig.txt](https://github.com/chrisbra/vim-diff-enhanced/files/843070/samplexity.h.orig.txt)

**Comment by chrisbra** [comment]
patience diff algorithm usually only works best with certain input files and does not generally provide better results. So it depends on your files to diff. The test includes some samples.
