### ISSUE TITLE
Vim unable to find diff when a multiple worktrees are generated

### ISSUE THREAD

**Issue by kairav** [chrisbra/vim-diff-enhanced#18]
I have checked out a git repository. I created multiple worktrees for the same repository. When I try to use git diff from the non default git directory, vim diff and enhanced diff doesnt seem to work. Any fix?

Thanks

**Comment by chrisbra** [comment]
please use `:let g:enhanced_diff_debug=1` before executing your diff. Then after you have done so, use `:messages` and check the command that has been used to generate the diff. Test this command on the commandline (you might need to change the filenames, as those are temporary file names generated by Vim).

**Comment by chrisbra** [comment]
no response, closine.
