### ISSUE TITLE
no inline diffs are shown

### ISSUE THREAD

**Issue by albasili** [chrisbra/vim-diff-enhanced#19]
Is there anything that needs to be configured in order to get inline differences highlighted instead of the whole line?

I've tried with 'patience' and 'histogram' without success. My sample buffers are 
first buffer:
```
test
```
second buffer:
```
this test;
```

The only caveat is that these buffers are not saved to any file... Would that make a difference?

**Comment by chrisbra** [comment]
what do you mean with inline differences highlighted?

**Comment by albasili** [comment]
I would expect that both 'this' and ';' are highlighted since they are part of the second buffer but nite the first, while the word 'test' should not. 

You habe in your readme a picture that shows this behavior at the bottom of the buffer (act and ib).

**Comment by chrisbra** [comment]
if git diff --diff-algorithm=patience does not show it, then there is no way, vim-diff-enhanced can show it. As written in the README, patience algorithm might not always work.
