### ISSUE TITLE
Any chance this'll work on stable 7.4 versions again?

### ISSUE THREAD

**Issue by Roy-Orbison** [chrisbra/vim-diff-enhanced#20]
I mean those packages with LTS distro versions, even CentOS 7, that don't support `systemlist`.

**Comment by Roy-Orbison** [comment]
Even if just hacked in like this:

	diff --git a/autoload/EnhancedDiff.vim b/autoload/EnhancedDiff.vim
	index f473c03..be2e236 100644
	--- a/autoload/EnhancedDiff.vim
	+++ b/autoload/EnhancedDiff.vim
	@@ -137,6 +137,12 @@ function! EnhancedDiff#ConvertToNormalDiff(list) "{{{2
	   endfor
	   return result
	 endfunction
	+function! EnhancedDiff#SysList(cmd)
	+  if exists('*systemlist')
	+    return systemlist(a:cmd)
	+  endif
	+  return split(system(a:cmd), '\n')
	+endfunction
	 function! EnhancedDiff#Diff(...) "{{{2
	   let cmd=(exists("a:1") ? a:1 : '')
	   let arg=(exists("a:2") ? a:2 : '')
	@@ -153,7 +159,7 @@ function! EnhancedDiff#Diff(...) "{{{2
	   if get(g:, 'enhanced_diff_debug', 0)
		 sil echomsg "Executing diff command: ". s:diffcmd . ' '. join(s:diffargs, ' ')
	   endif
	-  let difflist=systemlist(s:diffcmd. ' '. join(s:diffargs, ' '))
	+  let difflist=EnhancedDiff#SysList(s:diffcmd. ' '. join(s:diffargs, ' '))
	   call s:ModifyPathAndCD('-')
	   if v:shell_error < 0 || v:shell_error > 1
		 " An error occured
	diff --git a/plugin/EnhancedDiff.vim b/plugin/EnhancedDiff.vim
	index 7c414dc..c7b5cb4 100644
	--- a/plugin/EnhancedDiff.vim
	+++ b/plugin/EnhancedDiff.vim
	@@ -16,11 +16,11 @@
	 let s:cpo= &cpo
	 if exists("g:loaded_enhanced_diff") || &cp
		 finish
	-elseif !exists("*systemlist")
	-    echohl WarningMsg
	-    echomsg "The EnhancedDiff Plugin needs a newer Vim (or NeoVim)"
	-    echohl Normal
	-    finish
	 endif
	 set cpo&vim
	 let g:loaded_enhanced_diff = 1

**Comment by chrisbra** [comment]
If you make this:

> function! EnhancedDiff#SysList(cmd)

`function! s:SysList(cmd)` and then call it like `s:SysList(cmd)` it would be ready for a PR ;)

Thanks.
