### ISSUE TITLE
EnhancedDiffIgnorePat with bang doest not clear `g:enhanced_diff_ignore_pat`

### ISSUE THREAD

**Issue by liushapku** [chrisbra/vim-diff-enhanced#22]
In the command definition `<q-bang>` expands to `"!"` and `if "!"` evaluates to false. 
We need either use `if a:bang is "!"` or change `<q-bang>` to `<bang>0`

**Comment by liushapku** [comment]
Is it possible to change the `g:enhanced_diff_ignore_pat` to a buffer-local variable so that different filetypes can have different ignore patterns? Usually, we do not want to apply the same pattern to all different file types

By the way, this is a great plugin. Very helpful.Thank you.

**Comment by chrisbra** [comment]
Thanks for the feedback, I kind of expected a request for buffer-local variables, but thought perhapse nobody would actually need it. So does 15ffc86f55201b37144444a40a96b285d05400d2 fix your buffer-local problem?

**Comment by liushapku** [comment]
Thanks @chrisbra. That works.

I made one more comment on your [15ffc86](https://github.com/chrisbra/vim-diff-enhanced/commit/15ffc86f55201b37144444a40a96b285d05400d2) commit. Please check.

**Comment by jmarrec** [comment]
I'm hijacking this thread and apologize in advance, but I don't think this warrants opening an "issue", I'm just asking for help... and this is related.

 I'm trying to setup a an ignore pattern and having trouble with it.

I have a bunch of segments such as the one below, and I want to exclude anything that relates to Vertex (they are subject to floating point rounding errors).

```
  {50366d5b-0fdd-4629-b64b-66289679ead1}, !- Handle
  Shading Surface 98,                     !- Name
  ,                                       !- Construction Name
  {e3bf025a-f67c-487b-bb24-281a0e4bfc19}, !- Shading Surface Group Name
  ,                                       !- Transmittance Schedule Name
  ,                                       !- Number of Vertices
  68.1297071687243, 15.9501665365874, 3.45098469391719, !- X,Y,Z Vertex 1 {m}
  68.4208113794691, 15.9501665365874, 3.45098469391719, !- X,Y,Z Vertex 2 {m}
  68.7547128870579, 19.7728066901888, 3.45098469391718, !- X,Y,Z Vertex 3 {m}
  68.4658129093403, 19.7980416435478, 3.45098469391719; !- X,Y,Z Vertex 4 {m}
```

This works in vim when I want to search for such a pattern: `:/^[^!]\+!- X,Y,Z Vertex \d {m}$ `.

So I'm typing: `EnhancedDiffIgnorePat ^[^!]\+!- X,Y,Z Vertex \d {m}$` (I tried  `EnhancedDiffIgnorePat /^[^!]\+!- X,Y,Z Vertex \d {m}$/` too). Which does nothing, but perhaps I just need to update. So I type `:diffupdate`. Still nothing, these lines are still highlighted.

**Am I missing something? Do I need to use a specific algorithm such as Patience or histogram for the patterns to work?**

----

Also, If I wanted to set that in my .vimrc, you any of these two work? Do I need the quotes?

```
" Local only
au FileType myfiletype let b:enhanced_diff_ignore_pat = "/^[^!]\+!- X,Y,Z Vertex \d {m}$/"

" Global
let g:enhanced_diff_ignore_pat = "/^[^!]\+!- X,Y,Z Vertex \d {m}$/"
```

And thank you for this great plugin!

**Comment by jmarrec** [comment]
Hum, it seems that if I type these two after I launched macvim:

```
EnhancedDiffIgnorePat ^[^!]\+!- X,Y,Z Vertex \d {m}$
EnhancedDiff histogram
```

Then it works. Perhaps EnhancedDiff isn't enabled by default?

I've tried this in .vimrc:

```
" started In Diff-Mode set diffexpr (plugin not loaded yet)
if &diff
    let &diffexpr='EnhancedDiff#Diff("git diff", "--diff-algorithm=histogram")'
endif
" exclude vertex changes for myfiletype type files
au FileType myfiletype let b:enhanced_diff_ignore_pat = '^[^!]\+!- X,Y,Z Vertex \d {m}$'
```

![screen shot 2017-09-28 at 12 24 31 pm](https://user-images.githubusercontent.com/5479063/30961952-41a0eeb8-a448-11e7-8b81-7662ad09363b.png)

If I remove the quotes eg `au FileType myfiletype let b:enhanced_diff_ignore_pat = ^[^!]\+!- X,Y,Z Vertex \d {m}$` or if I try `au FileType myfiletype let b:enhanced_diff_ignore_pat = /^[^!]\+!- X,Y,Z Vertex \d {m}$/`I get "Invalid expression" error.

I'm not sure how I'm supposed to store the regex pattern and/or escape it properly.

**Comment by jmarrec** [comment]
I don't know vimscript, but https://github.com/chrisbra/vim-diff-enhanced/blob/master/autoload/EnhancedDiff.vim#L55 makes me think it expects a list.

So I've tried:

    au FileType myfiletype let b:enhanced_diff_ignore_pat = ['^[^!]\+!- X,Y,Z Vertex \d {m}$']

which doesn't throw any errors anymore (progress!). But the lines are still highlighted.

----

**EDIT:** re-reading the code I seem to understand you do need a replace pattern.

This works!

    au FileType eplus let b:enhanced_diff_ignore_pat = [['^[^!]\+!- X,Y,Z Vertex \d\+ {m}$', 'XXX']]

Perhaps the documentation (or FAQ section here) should be clearer on how to setup the enhanced_diff_ignore_pat, or the function should be modified to default to 'XXX' if no replacement pattern is found.



---- 

Example doc:

If you want to setup default ignore patterns, you can set up either the buffer or global `enhanced_diff_ignore_pat`. What this variable expects is a list of list such as:
 `[[patern1, replacement1],[pattern2, replacement2]]`. You can use 'XXX' for replacement patterns.

eg: 

    au FileType eplus let b:enhanced_diff_ignore_pat = [['^[^!]\+!- X,Y,Z Vertex \d\+ {m}$', 'XXX']]
    let g:enhanced_diff_ignore_pat = [['^[^!]\+!- X,Y,Z Vertex \d {m}$', 'XXX']]

**Comment by chrisbra** [comment]
suggested edits as PR welcomed.
