### ISSUE TITLE
CustomDiff fails on with Windows gvim and cygwin git

### ISSUE THREAD

**Issue by idbrii** [chrisbra/vim-diff-enhanced#3]
CustomDiff fails on Win7 with gvim from vim.org (7.4.0) and cygwin git (2.1.1).

```
:CustomDiff histogram
EnhancedDiff: git diff Error executing "git diff --diff-algorithm=histogram -U0 C:/Users/davidb/AppData/Local/Temp/VIoEC75.tmp C:/Users/davidb/AppData/Local/Temp/VInEC76.tmp"
EnhancedDiff: fatal: Invalid object name 'C'.
```

(I get a similar failure with or without `set shellslash`. I haven't figured out changing 'shell' to bash, but that might fix it.)

Looks like since the v:fname_in/out path names assume git will understand the same kinds of paths as gvim, but cygwin doesn't understand drive letters it all falls down. I'm not sure if there's something you want to fix (I should probably use msysgit, but it's too far removed from shell-useful).

I can work around it by making the paths relative (in ~/.vim/after/plugin/enhanceddiff.vim) with `:cd $TEMP`:

```
if has('win32')
    function! s:CustomDiffAlgComplete(A,L,P)
        return "myers\nminimal\ndefault\npatience\nhistogram"
    endf
    command! -nargs=1 -complete=custom,s:CustomDiffAlgComplete CustomDiff :cd $TEMP | let &diffexpr='EnhancedDiff#Diff("git diff", "--diff-algorithm=<args>")'|:diffupdate
endif
```

Of course once I cd again (or immediately if I had autochdir enabled), then it's broken again.

**Comment by chrisbra** [comment]
Oh, I see. Can you  check, if current head works for you? I changed it to always cd into the temporary directory for windows before doing the diff.

**Comment by idbrii** [comment]
On 373e1877bb09466a16f09cc380c4f56ca7bf7e8a, I get errors:

```
:CustomDiff histogram
Error detected while processing :
E810: Cannot read or write temp files
E97: Cannot create diffs

:diffupdate
Error detected while processing function diffusable#updatediff..EnhancedDiff#Diff..<SNR>250_ModifyPathAndCD:
line    5:
E344: Can't find directory "\-" in cdpath
E472: Command failed
E344: Can't find directory "\-" in cdpath
E472: Command failed


:Verbose echo &cdpath
,,
```

Not sure where the hyphen is coming from.

**Comment by chrisbra** [comment]
Shoot. cd - worked on linux so I assumed this works on Windows as well. Well, I have just fixed that now differently. Thanks for reporting back.

**Comment by idbrii** [comment]
Verified with test/4/ on 389e02e100ffedf7474ce8924512fac37f846a4d (with my workaround removed).

Thanks for the quick fix! I look forward to some tougher diffs to use this on.
