### ISSUE TITLE
consider "namespacing" the commands

### ISSUE THREAD

**Issue by justinmk** [chrisbra/vim-diff-enhanced#4]
PatienceDiff, DisableEnhancedDiff, CustomDiff, all have different prefixes. Plugins are more usable and discoverable if they namespace their commands, e.g.:

```
Ediff
EdiffPatience
EdiffDisable
EdiffCustom
...
```
- This also helps users intuit which command comes from where, without having to dig through the documentation after seeing a command appear in wildmenu.
- Instead of polluting the completion space of `C`, `P`, `D`, etc., the plugin only pollutes _one_ prefix space: `E`. wildmenu is less useful if each plugin creates a bunch of random non-namespaced command names.

**Comment by chrisbra** [comment]
Am 2015-04-15 00:12, schrieb Justin M. Keyes:

> PatienceDiff, DisableEnhancedDiff, CustomDiff, all have different
> prefixes. Plugins are more usable and discoverable if they namespace
> their commands, e.g.:
> 
> Ediff
> EdiffPatience
> EdiffDisable
> EdiffCustom
> ...
> 
> This also helps users intuit which command comes from where, without
> having to dig through the documentation after seeing a command appear
> in wildmenu.

PatienceDiff is just a shortcut for CustomDiff patience, which is 
supposed to
be the only actual command.

Disable is also just a convenience wrapper to set the diffexpr to empty.

Perhaps I should call it EnhancedDiff patience...

Best,
Christian

**Comment by justinmk** [comment]
Thanks!

> Perhaps I should call it EnhancedDiff patience

I'd prefer that to avoid the `P` space crowding, but I got 90% of what I asked so I won't complain :)

**Comment by chrisbra** [comment]
;) (noted)
