### ISSUE TITLE
readme corrections

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/vim-diff-enhanced#5]
Hello,

> This plugin allows to make use of the Patience diff algorithm for generating diffs to use with Vim.

Probably mean:

This plugin allows you to make use of the Patience diff algorithm for generating diffs to use with Vim. 

> You can also customize you setup

your setup

Is it really `:CustomDiff histogram` or `:EnhancedDiff <algorithm>` as mentioned further below?

> Note: Those 2 commands use internally git to generate the diffs. 

Probably needs revising. Are you saying git is used internally to generate the diffs?

**Comment by chrisbra** [comment]
Thanks, I have updated the documentation. It should be clearer now.
