### ISSUE TITLE
Setting patience diff as the default

### ISSUE THREAD

**Issue by aktau** [chrisbra/vim-diff-enhanced#6]
Hi Chistian,

I know this is going to sound like a stupid question, but I can't figure it out. How do I apply `:PatienceDiff` on vim startup (so that when I run vimdiff, all my files get diffed with the patience algorithm)?

Putting `PatienceDiff` in my .vimrc yields:

```
line  449:
E492: Not an editor command: PatienceDiff
```

While if I execute it after the file I loaded by typing `:PatienceDiff`, everything works fine.

_EDIT_: I have made sure to put the `PatienceDiff` invocation after loading the `vim-diff-enhanced` plugin with Vundle.

**Comment by chrisbra** [comment]
It is not entirely obvious from the documentation, but it should work, if you simply set in your .vimrc:

```
:let &diffexpr='EnhancedDiff#Diff("git diff", "--diff-algorithm=patience")'
```

I'll document that part.

**Comment by aktau** [comment]
Thanks, that seems to work nicely!

The only sad thing appears to be that it's quite a bit slower than how vim regularly does things. Perhaps because of the extra temporary files or something.

Unsure if this is caused by vim-diff-enhanced or some other plugin I'm using, but when I run [execsnoop](https://github.com/brendangregg/perf-tools/blob/master/execsnoop) I see:

```
  7223   7067 /bin/zsh -c (git diff --diff-algorithm=patience -U0 /tmp/vtMtOaA/62 /tmp/vtMtOaA/63) >/tmp/vtMtOaA/65 2>&1
  7227   7067 /bin/zsh -c (git diff --diff-algorithm=patience -U0 /tmp/vtMtOaA/62 /tmp/vtMtOaA/63) >/tmp/vtMtOaA/66 2>&1
```

Appearing. Which seems to imply that it's doing double work.

**Comment by aktau** [comment]
Addendum: it seems to have nothing to do with vim-diff-enhanced, regular vim diffing provokes:

```
  9517   8711 /bin/zsh -c diff -a /tmp/vkI3T3i/244 /tmp/vkI3T3i/245 >/tmp/vkI3T3i/246 2>&1
  9519   8711 /bin/zsh -c diff -a /tmp/vkI3T3i/244 /tmp/vkI3T3i/245 >/tmp/vkI3T3i/246 2>&1
```

Might be that regular diff is just a bit faster. The only difference I see is that the output tmpfiles are the same here.

**Comment by chrisbra** [comment]
Regular diff is probably faster, since I need to parse the git-diff output and translate it into ed style diff. That might take some time.

**Comment by xanderman** [comment]
You can also set patience diff as default by creating ~/.vim/after/plugin/patiencediff.vim with the following content:

" This can't go in .vimrc, because :PatienceDiff isn't available
if !exists(":PatienceDiff")
  " This block is optional, but will protect you from errors if you uninstall vim-diff-enhanced
  " or share your config across machines
  finish
endif
PatienceDiff

Some people think 'after' files are evil, but I hold that only _plugins_ with 'after' files are evil. End users have completely valid reasons for using them (like this!).

**Comment by chrisbra** [comment]
@xanderman good remark. This has the additional advantage of should the implementation of the EnhancedDiff#Diff() function sometimes in the future change, you don't need to change anything. I'll add this to the documentation of the plugin.
