### ISSUE TITLE
Got "E97: cannot create diffs"

### ISSUE THREAD

**Issue by walkingsparrow** [chrisbra/vim-diff-enhanced#7]
I am use the latest vim-diff-enhanced. And use Plug to manage the plugins.

The error message when I run 'PatienceDiff' and any other commands in this plugin.

```
Searching for "/usr/local/google/home/hqian/.vim/plugged/vim-diff-enhanced/autoload/EnhancedDiff.vim"
chdir(/usr/local/google/home/hqian/.vim/plugged/vim-diff-enhanced/autoload)
fchdir() to previous dir
sourcing "/usr/local/google/home/hqian/.vim/plugged/vim-diff-enhanced/autoload/EnhancedDiff.vim"
finished sourcing /usr/local/google/home/hqian/.vim/plugged/vim-diff-enhanced/autoload/EnhancedDiff.vim
calling function EnhancedDiff#Diff
calling function EnhancedDiff#Diff..<SNR>166_DiffInit
calling function EnhancedDiff#Diff..<SNR>166_DiffInit..<SNR>166_ModifyPathAndCD
function EnhancedDiff#Diff..<SNR>166_DiffInit..<SNR>166_ModifyPathAndCD returning '/tmp/vCmMcn3/39'
continuing in function EnhancedDiff#Diff..<SNR>166_DiffInit
calling function EnhancedDiff#Diff..<SNR>166_DiffInit..<SNR>166_ModifyPathAndCD
function EnhancedDiff#Diff..<SNR>166_DiffInit..<SNR>166_ModifyPathAndCD returning '/tmp/vCmMcn3/40'
continuing in function EnhancedDiff#Diff..<SNR>166_DiffInit
function EnhancedDiff#Diff..<SNR>166_DiffInit returning #0
continuing in function EnhancedDiff#Diff
Calling shell to execute: "(git diff --diff-algorithm=patience -U0 /tmp/vCmMcn3/39 /tmp/vCmMcn3/40) >/tmp/vCmMcn3/42 2>&1"

calling function EnhancedDiff#Diff..<SNR>166_ModifyPathAndCD
function EnhancedDiff#Diff..<SNR>166_ModifyPathAndCD returning '\-'
continuing in function EnhancedDiff#Diff
calling function EnhancedDiff#Diff..EnhancedDiff#ConvertToNormalDiff
function EnhancedDiff#Diff..EnhancedDiff#ConvertToNormalDiff returning []
continuing in function EnhancedDiff#Diff
function EnhancedDiff#Diff returning #0
E97: Cannot create diffs
```

**Comment by chrisbra** [comment]
Can you set the variable g:enhanced_diff_debug to 1 and run :PatienceDiff again? Can you show the output of the command (there should be a file EnhancedDiff_Normal.txt and EnhancedDiff_default.txt).

**Comment by chrisbra** [comment]
This looks a little bit, like it can't create temp files. could that be the case?

**Comment by chrisbra** [comment]
Any update?

**Comment by walkingsparrow** [comment]
I set g:enhanced_diff_debug to be 1, and compare two files that have 2 lines difference.
EnhancedDiff_normal.txt is empty. And EnhancedDiff_default.txt has

```
1c1
< line1
---
> line2
```

And I can write to /tmp. In the example that I show in the first post, `/tmp/vCmMcn3` was created but the files `39` and `40` are not created.

By the way, because I do not have too much space in / and some of my work needs large temp space, I set the environment variable `$TMP` to be on another disk that has enough space, which my work can use. So some programs are still using the system `/tmp`, and others that uses `$TMP` can have more space. I am not sure whether this could cause problems.

**Comment by walkingsparrow** [comment]
But running `TMP=/tmp vimdiff file1 file2` still gives me the same error.

**Comment by chrisbra** [comment]
I am almost out of clues. Can you do
`:breakadd func EnhancedDiff#Diff`
`:PatienceDiff`
`:windo :diffthis`
and step manually through the diff() function? It isn't too long and should be fairly straight forward. simply keep pressing 'n' (see also the help at `:h debug-mode`)?
Watch out for errors in the system/systemlist function call (and check the argument of that function s:diffargs that is set up in s:DiffInit()

**Comment by walkingsparrow** [comment]
The error appears at the end of the debugging:

```
function EnhancedDiff#Diff
line 45: endif
>n
function EnhancedDiff#Diff
line 45: End of function
>n
E97: Cannot create diffs
```

**Comment by chrisbra** [comment]
hm, at the place where the systemlist() function is called, do something like this:

```
if exists("*systemlist")
    let difflist=systemlist(s:diffcmd. ' '. join(s:diffargs, ' '))
else
    let difflist=split(system(s:diffcmd. ' '. join(s:diffargs, ' ')), "\n")
endif
```

Can you please show the value of `s:diffargs` (e.g. `:echo join(s:diffargs, ' ')` ) The output should look like this:
`--diff-algorithm=patience -U0 /tmp/vkmCzO2/10 /tmp/vkmCzO2/11`
Can you check, that those filenames are created and contain your expected input?

**Comment by talha131** [comment]
@chrisbra I hope you are still supporting this plugin.

I get the same error mentioned in the post. I am using OS X and Vim 8.0.

I have tried all the steps you mentioned. The output of `:echo join(s:diffargs, ' ')` is

```
--diff-algorithm=patience -U0 /var/folders/v2/z4v0_njx6px9xx9d2wx0vf8c0000gp/T/vm1LQnu/7 /var/folders/v2/z4v0_njx6px9xx9d2wx0vf8c0000gp/T/vm1LQnu/8
```

Those files are not created at all. `/var/folders/v2/z4v0_njx6px9xx9d2wx0vf8c0000gp/T/vm1LQnu/` folder is empty.

Can you please help me here?

**Comment by talha131** [comment]
I also ran the test. I got failure with test 1.

I removed break from the `test.sh` to see which tests pass and which fail. Only test three passed. All rest of the tests failed.

**Comment by talha131** [comment]
At [this line](https://github.com/chrisbra/vim-diff-enhanced/blob/master/autoload/EnhancedDiff.vim#L164), `echo difflist` is empty `[]`.

```
call writefile(difflist, v:fname_out)
```

**Update 1:**

Code enters `EnhancedDiff#ConvertToNormalDiff`. The result of this method is `[]`, although a long list is passed as an argument to it.

**Comment by talha131** [comment]
To the possibility that Vim does not write permission for the temp folders, I set `$TMP` and `$TMPDIR` to a directory in my home folder.

```
let $TMP='/Users/talha/.vimTemp/'
let $TMPDIR='/Users/talha/.vimTemp/'
```

This time the result is

```
['--diff-algorithm=patience', '-U0', '/Users/talha/.vimTemp/vZsHKDu/15', '/Users/talha/.vimTemp/vZsHKDu/16']
```

This directory `/Users/talha/.vimTemp/vZsHKDu` was created in `/Users/talha/.vimTemp/` folder. But file 15 and 16 didn't exist. Whole folder is empty.

**Comment by chrisbra** [comment]
so what happens if you then do: `system('git '. join(s:diffargs, ' '))`? Or when you call `:! git \<c-r>=join(s:diffargs, ' ')<cr><cr>`

**Comment by talha131** [comment]
I think you meant doing `system('git diff '. join(s:diffargs, ' '))` because `s:diffargs` is just

```
['--diff-algorithm=patience', 
'-U0', 
'/Users/talha/.vimTemp/v2LVe4v/7', 
'/Users/talha/.vimTemp/v2LVe4v/8']
```

I added `system('git diff '. join(s:diffargs, ' '))` before [this line](https://github.com/chrisbra/vim-diff-enhanced/blob/master/autoload/EnhancedDiff.vim#L150). It just added error E810.

` :! git \<c-r>=join(s:diffargs, ' ')<cr><cr>` `s:diffargs` is local to the script. I don't understand how can it work from command line. I tried and got the error Undefined variable `s:diffargs`.

**Comment by chrisbra** [comment]
On Fr, 10 Feb 2017, Talha Mansoor wrote:

> I think you meant doing `system('git diff '. join(s:diffargs, ' '))` because `s:diffargs` is just
> 
> ```
> ['--diff-algorithm=patience', 
> '-U0', 
> '/Users/talha/.vimTemp/v2LVe4v/7', 
> '/Users/talha/.vimTemp/v2LVe4v/8']
> ```
> 
> I added `system('git diff '. join(s:diffargs, ' '))` before [this line](https://github.com/chrisbra/vim-diff-enhanced/blob/master/autoload/EnhancedDiff.vim#L150). It just added error E810.

Okay, somehow we cannot execute git diff. Just to make sure: You do have 
git in your path? What shell are you using? Any particular shell 
settings?
> 
> ` :! git \<c-r>=join(s:diffargs, ' ')<cr><cr>` `s:diffargs` is local to the script. I don't understand how can it work from command line. I tried and got the error Undefined variable `s:diffargs`.

Yeah sorry. write current buffer as <name>.new: Does :! git diff-algorithm=patience -U0 % %.new work?

**Comment by talha131** [comment]
@chrisbra This is what worked for me from command line

```
!git diff --diff-algorithm=patience -U0 -- % %.new
```

Notice I added `diff` after git. And added `--` before file paths  `% %.new`.

My shell is `shell=/usr/local/bin/fish` though I have tried setting it to `/bib/bash` to no effect.

Git is certainly in my path because I can run Vim Fugitive and its diff.

**Comment by talha131** [comment]
I think I have fixed the issue. Let me check.  I will open a PR shortly.

**Comment by talha131** [comment]
@chrisbra Here you go 

https://github.com/chrisbra/vim-diff-enhanced/pull/14

Kindly review and merge.
