### ISSUE TITLE
Can't change diff algorithm

### ISSUE THREAD

**Issue by oblitum** [chrisbra/vim-diff-enhanced#8]
Just installed the plugin and tried it inside a git repository with `git difftool HEAD~2 HEAD~`. In the first file that I've tried `:EnhacedDiff <any-algorithm>`, the diff style didn't change (tried many times)~~, but when following for the next file in the changeset, the diff algorithm applied~~, nor did it get change for any of the following files in the changeset.

Vim 7.4.1016, Git 2.7.0. Using inside TMUX on Archlinux.

**Comment by oblitum** [comment]
Sorry. To tell the truth I'm not sure whether it's changing the algorithm in any case. It doesn't matter whether I set it or not, I'm getting the same always.

**Comment by chrisbra** [comment]
Hm, I am not sure I follow. git difftool does not seem to generate any diffs for me.

**Comment by oblitum** [comment]
@chrisbra you should have it configured for vimdiff first. `git difftool --tool=vimdiff HEAD~2 HEAD~`, or set it permanently in your `.gitconfig`.

**Comment by chrisbra** [comment]
Try adding this to your .vimrc:

``` viml
  " started In Diff-Mode set diffexpr (plugin not loaded yet)
  if &diff
    let &diffexpr='EnhancedDiff#Diff("git diff", "--diff-algorithm=patience")'
  endif
```

From my testing this works.

**Comment by chrisbra** [comment]
However manually setting turning on the patience diff algorithm should work, and did also work from my testing. So I can't replicate your problem. Chances are however, that for your test case the patience diff algorithm simply did not produce a different result.

**Comment by oblitum** [comment]
I should get some repo with a changeset where I can see any difference between difference algorithms o_O....

Maybe another time, will close it for now, thanks for the effort.
