### ISSUE TITLE
:h EnhancedDiff doesn't work

### ISSUE THREAD

**Issue by 1-61803** [chrisbra/vim-diff-enhanced#9]
I get `E149: Sorry, no help for EnhancedDiff`.

**Comment by chrisbra** [comment]
Am 2016-03-01 12:31, schrieb 1-61803:

> I get E149: Sorry, no help for EnhancedDiff.

How did you install it?

**Comment by 1-61803** [comment]
`git clone https://github.com/chrisbra/vim-diff-enhanced.git ~/.vim/bundle/vim-enhanced-diff`

**Comment by chrisbra** [comment]
Am 2016-03-01 12:45, schrieb 1-61803:

> git clone https://github.com/chrisbra/vim-diff-enhanced.git
> ~/.vim/bundle/vim-enhanced-diff

And you are using pathogen?

**Comment by 1-61803** [comment]
Yes

**Comment by chrisbra** [comment]
Am 2016-03-01 12:47, schrieb 1-61803:

> Yes

Then it should have run helptags.

Can you please run `:helptags ~/.vim/bundle/vim-enhanced-diff/doc`

See if that works. (you might need to restart vim).

**Comment by 1-61803** [comment]
Manually running `helptags` made it work. I don't know if that should have happened when installing the plugin in the first place.

**Comment by chrisbra** [comment]
Am 2016-03-01 12:56, schrieb 1-61803:

> Manually running helptags made it work. I don't know if that should
> have happened when installing the plugin in the first place.

It should and this happens usually by pathogen. I don't know, why it 
wouldn't do it however.

**Comment by 1-61803** [comment]
If this happens with `pathogen` then you might want to add `:helptags ~/.vim/bundle/vim-enhanced-diff/doc` to the `README`.

**Comment by chrisbra** [comment]
Am 2016-03-01 15:11, schrieb 1-61803:

> If this happens with pathogen then you might want to add :helptags
> ~/.vim/bundle/vim-enhanced-diff/doc to the README.

indeed. I'll update the README

**Comment by somini** [comment]
If you have Pathogen, you can actually run `:Helptags` and all the tags for all your plugins will be updated.

**Comment by chrisbra** [comment]
That's what I used in the commit.
